version: '3.3'

services:
  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bot
    container_name: app_mysql
    ports:
      - '3306:3306'
    expose:
      - 3306
